// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJpBzqh89_XRmc7OwyrdgZb1INdgWkbs',
    appId: '1:737213156116:web:91d43bb66837bea4ea9001',
    messagingSenderId: '737213156116',
    projectId: 'chatmate-f2acd',
    authDomain: 'chatmate-f2acd.firebaseapp.com',
    storageBucket: 'chatmate-f2acd.appspot.com',
    measurementId: 'G-D51BM2K8QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_hZvvmu4bAsgXArYuwKIkzEgIlpyA1oE',
    appId: '1:1003823911782:android:49a6b3734b51b69986aea7',
    messagingSenderId: '1003823911782',
    projectId: 'chatmate-25f72',
    storageBucket: 'chatmate-25f72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0x7PZj0ll_fNnZEsvuRc0X3hJ8zsIV5A',
    appId: '1:1003823911782:ios:f653fc5a5728218486aea7',
    messagingSenderId: '1003823911782',
    projectId: 'chatmate-25f72',
    storageBucket: 'chatmate-25f72.appspot.com',
    iosBundleId: 'com.example.chatmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc-N3DxAcEMX0NMTT_J9Fk30omhJIUIcg',
    appId: '1:737213156116:ios:0c7e32cc70c927a5ea9001',
    messagingSenderId: '737213156116',
    projectId: 'chatmate-f2acd',
    storageBucket: 'chatmate-f2acd.appspot.com',
    iosBundleId: 'com.example.chatmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzJpBzqh89_XRmc7OwyrdgZb1INdgWkbs',
    appId: '1:737213156116:web:770fdf100e06e845ea9001',
    messagingSenderId: '737213156116',
    projectId: 'chatmate-f2acd',
    authDomain: 'chatmate-f2acd.firebaseapp.com',
    storageBucket: 'chatmate-f2acd.appspot.com',
    measurementId: 'G-PQYW610JDZ',
  );
}